const Languages = {
    "ar" : {
        "name" : "العربية",
        "locale" : "ar",
        "__language__" : "اللغة",
        "__theme__" : "موضوع",
        "__opacity__" : "العتامه",
        "__custom_settings__" : "إعدادات مخصصة",
        "__custom_settings_desc__" : "انقر فوق الزر لاستعادة الأنواع والدبابيس والسمة.",
        "__restore__" : "يستعيد",
        "__data_storage__" : "تخزين البيانات",
        "__disk_space_usage__" : "استخدام مساحة القرص:",
        "__click_to_remove__" : "KB ، انقر فوق الزر لإزالة جميع البيانات.",
        "__clear_all_data__" : "مسح جميع البيانات",
        "__show_hide_list__" : "إظهار / إخفاء القائمة",
        "__always_on_top__" : "دائما في المقدمة",
        "__minimize__" : "تصغير",
        "__quit__" : "انهاء",
        "__create__" : "خلق",
        "__new_list__" : "قائمة جديدة",
        "__settings__" : "اعدادات",
        "__pin__" : "دبوس",
        "__unpin__" : "حذف",
        "__new_subtask__" : "مهمة فرعية جديدة",
        "__remove__" : "أبعد",
        "__just_now__" : "منذ لحظة واحدة",
        "__sec__" : "ثانية",
        "__min__" : "دقائق",
        "__hr__" : "ساعات",
        "__day__" : "أيام",
        "__week__" : "أسابيع",
        "__month__" : "أشهر",
        "__year__" : "سنوات",
        "__filter__" : "راووق",
        "__show_incomplete_tasks_only__" : "إظهار المهام غير المكتملة فقط",
        "__show_completed_tasks_only__" : "إظهار المهام المكتملة فقط",
        "__task__" : "مهمة",
        "__report__" : "تقرير",
        "__show_hide_side_nav__" : "إظهار / إخفاء التنقل الجانبي",
        "__btn_week__" : "أسبوع",
        "__btn_month__" : "شهر",
        "__btn_year__" : "سنة",
        "__btn_activity__" : "نشاط",
        "__btn_quantity__" : "كم",
        "__time_period__" : "الفترة الزمنية",
        "__incompleted__" : "غير مكتمل",
        "__completed__" : "اكمال",
        "__total__" : "مجموع"
    },
    "de" : {
        "name" : "Deutsch",
        "locale" : "de",
        "__language__" : "Sprache",
        "__theme__" : "Thema",
        "__opacity__" : "Undurchsichtigkeit",
        "__custom_settings__" : "Benutzerdefinierte Einstellungen",
        "__custom_settings_desc__" : "Klicken Sie auf die Schaltfläche, um Sorten, Pins und Themen wiederherzustellen.",
        "__restore__" : "Wiederherstellen",
        "__data_storage__" : "Datenspeicherung",
        "__disk_space_usage__" : "Speicherplatznutzung: ",
        "__click_to_remove__" : "KB, klicken Sie auf die Schaltfläche, um alle Daten zu entfernen.",
        "__clear_all_data__" : "Alle Daten löschen",
        "__show_hide_list__" : "Liste ein- / ausblenden",
        "__always_on_top__" : "Immer im Vordergrund",
        "__minimize__" : "Minimieren",
        "__quit__" : "Verlassen",
        "__create__" : "Aufgabe erstellen",
        "__new_list__" : "Neue Liste",
        "__settings__" : "Einstellungen",
        "__pin__" : "Stecknadel",
        "__unpin__" : "Losheften",
        "__new_subtask__" : "Neue Unteraufgabe",
        "__remove__" : "Entfernen",
        "__just_now__" : "gerade eben",
        "__sec__" : "Sekunden vor",
        "__min__" : "Minuten vor",
        "__hr__" : "Stunden vor",
        "__day__" : "Tagen vor",
        "__week__" : "Wochen vor",
        "__month__" : "Monate vor",
        "__year__" : "Jahr vor",
        "__filter__" : "Filter",
        "__show_incomplete_tasks_only__" : "Nur unerledigte Aufgaben anzeigen",
        "__show_completed_tasks_only__" : "Nur erledigte Aufgaben anzeigen",
        "__task__" : "Aufgabe",
        "__report__" : "Bericht",
        "__show_hide_side_nav__" : "Seitennavigation ein- / ausblenden",
        "__btn_week__" : "Woche",
        "__btn_month__" : "Monat",
        "__btn_year__" : "Jahr",
        "__btn_activity__" : "Aktivität",
        "__btn_quantity__" : "Menge",
        "__time_period__" : "Zeitraum",
        "__incompleted__" : "Unvollständig",
        "__completed__" : "Abgeschlossen",
        "__total__" : "Gesamt"
    },
    "en" : {
        "name" : "English",
        "locale" : "en",
        "__language__" : "Language",
        "__theme__" : "Theme",
        "__opacity__" : "Opacity",
        "__custom_settings__" : "Custom Settings",
        "__custom_settings_desc__" : "Click button to restore sorts, pins and theme.",
        "__restore__" : "Restore",
        "__data_storage__" : "Data Storage",
        "__disk_space_usage__" : "Disk space usage:",
        "__click_to_remove__" : "KB, click button to remove all the data.",
        "__clear_all_data__" : "Clear all data",
        "__show_hide_list__" : "Show / Hide List",
        "__always_on_top__" : "Always On Top",
        "__minimize__" : "Minimize",
        "__quit__" : "Quit",
        "__create__" : "Create",
        "__new_list__" : "New List",
        "__settings__" : "Settings",
        "__pin__" : "Pin",
        "__unpin__" : "Unpin",
        "__new_subtask__" : "New Subtask",
        "__remove__" : "Remove",
        "__just_now__" : "Just now",
        "__sec__" : "sec",
        "__min__" : "min",
        "__hr__" : "hr",
        "__day__" : "day",
        "__week__" : "week",
        "__month__" : "month",
        "__year__" : "year",
        "__filter__" : "Filter",
        "__show_incomplete_tasks_only__" : "Show incomplete tasks only",
        "__show_completed_tasks_only__" : "Show completed tasks only",
        "__task__" : "Task",
        "__report__" : "Report",
        "__show_hide_side_nav__" : "Show / Hide Side Navigation",
        "__btn_week__" : "Week",
        "__btn_month__" : "Month",
        "__btn_year__" : "Year",
        "__btn_activity__" : "Activity",
        "__btn_quantity__" : "Quantity",
        "__time_period__" : "Time Period",
        "__incompleted__" : "Incomplete",
        "__completed__" : "Completed",
        "__total__" : "Total"
    },
    "es" : {
        "name" : "Español",
        "locale" : "es",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidad",
        "__custom_settings__" : "Ajustes personalizados",
        "__custom_settings_desc__" : "Haga clic en el botón para restaurar las clasificaciones, los pines y el tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Almacenamiento de datos",
        "__disk_space_usage__" : "Uso de espacio en disco:",
        "__click_to_remove__" : "KB, haga clic en el botón para eliminar todos los datos.",
        "__clear_all_data__" : "Borrar todos los datos",
        "__show_hide_list__" : "Mostrar / Ocultar lista",
        "__always_on_top__" : "Siempre en la cima",
        "__minimize__" : "Minimizar",
        "__quit__" : "Renunciar",
        "__create__" : "Crear tarea",
        "__new_list__" : "Nueva lista",
        "__settings__" : "Configuración",
        "__pin__" : "Anclar",
        "__unpin__" : "Desanclar",
        "__new_subtask__" : "Nueva subtarea",
        "__remove__" : "Eliminar",
        "__just_now__" : "hace un momento",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "días",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "año",
        "__filter__" : "Filtro",
        "__show_incomplete_tasks_only__" : "Mostrar solo tareas incompletas",
        "__show_completed_tasks_only__" : "Mostrar solo tareas completadas",
        "__task__" : "Tarea",
        "__report__" : "Informe",
        "__show_hide_side_nav__" : "Mostrar / Ocultar navegación lateral",
        "__btn_week__" : "Semana",
        "__btn_month__" : "Mes",
        "__btn_year__" : "Año",
        "__btn_activity__" : "Actividad",
        "__btn_quantity__" : "Cantidad",
        "__time_period__" : "Período de tiempo",
        "__incompleted__" : "Incompleto",
        "__completed__" : "Completado",
        "__total__" : "Total"
    },
    "fr" : {
        "name" : "Française",
        "locale" : "fr",
        "__language__" : "Langue",
        "__theme__" : "Thème",
        "__opacity__" : "Opacité",
        "__custom_settings__" : "Paramètres personnalisés",
        "__custom_settings_desc__" : "Cliquez sur le bouton pour restaurer les tris, les épingles et le thème.",
        "__restore__" : "Restaurer",
        "__data_storage__" : "Stockage des données",
        "__disk_space_usage__" : "Utilisation de l'espace disque :",
        "__click_to_remove__" : "Ko, cliquez sur le bouton pour supprimer toutes les données.",
        "__clear_all_data__" : "Effacer toutes les données",
        "__show_hide_list__" : "Afficher / Masquer la liste",
        "__always_on_top__" : "Toujours au sommet",
        "__minimize__" : "Minimiser",
        "__quit__" : "Démissionner",
        "__create__" : "Créer une tâche",
        "__new_list__" : "Nouvelle liste",
        "__settings__" : "Paramètres",
        "__pin__" : "Épingler",
        "__unpin__" : "Désépingler",
        "__new_subtask__" : "Nouvelle sous-tâche",
        "__remove__" : "Enlever",
        "__just_now__" : "Il y a quelques instants",
        "__sec__" : "secondes",
        "__min__" : "minutes",
        "__hr__" : "heures",
        "__day__" : "jours",
        "__week__" : "semaines",
        "__month__" : "mois",
        "__year__" : "an",
        "__filter__" : "Filtre",
        "__show_incomplete_tasks_only__" : "Afficher uniquement les tâches incomplètes",
        "__show_completed_tasks_only__" : "Afficher uniquement les tâches terminées",
        "__task__" : "Tâche",
        "__report__" : "Rapport",
        "__show_hide_side_nav__" : "Afficher / Masquer la navigation latérale",
        "__btn_week__" : "Semaine",
        "__btn_month__" : "Mois",
        "__btn_year__" : "Année",
        "__btn_activity__" : "Activité",
        "__btn_quantity__" : "Quantité",
        "__time_period__" : "Période",
        "__incompleted__" : "Incomplet",
        "__completed__" : "Terminé",
        "__total__" : "Total"
    },
    "in" : {
        "name" : "हिंदी",
        "locale" : "hi",
        "__language__" : "भाषा",
        "__theme__" : "विषय",
        "__opacity__" : "अस्पष्टता",
        "__custom_settings__" : "कस्टम सेटिंग्स",
        "__custom_settings_desc__" : "प्रकार, पिन और विषय को पुनर्स्थापित करने के लिए बटन पर क्लिक करें।",
        "__restore__" : "पुनर्स्थापित करना",
        "__data_storage__" : "डेटा भंडारण",
        "__disk_space_usage__" : "डिस्क स्थान उपयोग:",
        "__click_to_remove__" : "KB, सभी डेटा को हटाने के लिए बटन पर क्लिक करें।",
        "__clear_all_data__" : "सभी डेटा साफ़ करें",
        "__show_hide_list__" : "सूची दिखाएं/छुपाएं",
        "__always_on_top__" : "हमेशा शीर्ष पर",
        "__minimize__" : "कम करके बताना",
        "__quit__" : "छोड़ना",
        "__create__" : "बनाना",
        "__new_list__" : "नई सूची",
        "__settings__" : "सेटिंग्स",
        "__pin__" : "पिन",
        "__unpin__" : "अनपिन",
        "__new_subtask__" : "नया उपकार्य",
        "__remove__" : "हटाना",
        "__just_now__" : "अभी-अभी",
        "__sec__" : "सेकंड",
        "__min__" : "मिनट",
        "__hr__" : "घंटे",
        "__day__" : "दिन",
        "__week__" : "कार्य-सप्‍ताह",
        "__month__" : "महीना",
        "__year__" : "सालों",
        "__filter__" : "छानना",
        "__show_incomplete_tasks_only__" : "केवल अधूरे कार्य दिखाएँ",
        "__show_completed_tasks_only__" : "केवल पूर्ण किए गए कार्य दिखाएँ",
        "__task__" : "नियत कार्य",
        "__report__" : "रिपोर्ट",
        "__show_hide_side_nav__" : "साइड नेविगेशन दिखाएं/छुपाएं",
        "__btn_week__" : "कार्य-सप्‍ताह",
        "__btn_month__" : "महीना",
        "__btn_year__" : "सालों",
        "__btn_activity__" : "गतिविधि",
        "__btn_quantity__" : "बड़ तादाद",
        "__time_period__" : "समय सीमा",
        "__incompleted__" : "अधूरा",
        "__completed__" : "पूरा किया",
        "__total__" : "कुल"
    },
    "it" : {
        "name" : "Italiana",
        "locale" : "it",
        "__language__" : "Lingua",
        "__theme__" : "Tema",
        "__opacity__" : "Opacità",
        "__custom_settings__" : "Impostazioni personalizzate",
        "__custom_settings_desc__" : "Fare clic sul pulsante per ripristinare ordinamenti, pin e tema.",
        "__restore__" : "Restaurare",
        "__data_storage__" : "Archiviazione dei dati",
        "__disk_space_usage__" : "Utilizzo dello spazio su disco:",
        "__click_to_remove__" : "KB, fare clic sul pulsante per rimuovere tutti i dati.",
        "__clear_all_data__" : "Cancella tutti i dati",
        "__show_hide_list__" : "Mostra / Nascondi elenco",
        "__always_on_top__" : "Sempre in primo piano",
        "__minimize__" : "Minimizzare",
        "__quit__" : "Dimettersi",
        "__create__" : "Creare",
        "__new_list__" : "Nuovo elenco",
        "__settings__" : "Impostazioni",
        "__pin__" : "Spilla",
        "__unpin__" : "Rimuovere",
        "__new_subtask__" : "Nuova sottoattività",
        "__remove__" : "Togliere",
        "__just_now__" : "Poco fa",
        "__sec__" : "secondo",
        "__min__" : "minuta",
        "__hr__" : "orario",
        "__day__" : "giorno",
        "__week__" : "settimana",
        "__month__" : "mese",
        "__year__" : "anno",
        "__filter__" : "Filtro",
        "__show_incomplete_tasks_only__" : "Mostra solo le attività incomplete",
        "__show_completed_tasks_only__" : "Mostra solo le attività completate",
        "__task__" : "Compito",
        "__report__" : "Rapporto",
        "__show_hide_side_nav__" : "Mostra / Nascondi navigazione laterale",
        "__btn_week__" : "Settimana",
        "__btn_month__" : "Mese",
        "__btn_year__" : "Anno",
        "__btn_activity__" : "Attività",
        "__btn_quantity__" : "Quantità",
        "__time_period__" : "Periodo di tempo",
        "__incompleted__" : "Incompleto",
        "__completed__" : "Finito",
        "__total__" : "Totale"
    },
    "jp" : {
        "name" : "日本語",
        "locale" : "ja",
        "__language__" : "言語",
        "__theme__" : "テーマ",
        "__opacity__" : "不透明",
        "__custom_settings__" : "カスタム設定",
        "__custom_settings_desc__" : "ボタンをクリックして、並べ替え、ピン、テーマを復元します。",
        "__restore__" : "戻す",
        "__data_storage__" : "データストレージ",
        "__disk_space_usage__" : "ディスク容量の使用量:",
        "__click_to_remove__" : "KB、ボタンをクリックしてすべてのデータを削除します。",
        "__clear_all_data__" : "すべてのデータをクリアする",
        "__show_hide_list__" : "リストの表示/非表示",
        "__always_on_top__" : "常にトップに",
        "__minimize__" : "最小化する",
        "__quit__" : "辞める",
        "__create__" : "タスクを作成",
        "__new_list__" : "新規リスト",
        "__settings__" : "設定",
        "__pin__" : "ピン",
        "__unpin__" : "解除",
        "__new_subtask__" : "新規サブタスク",
        "__remove__" : "取り去る",
        "__just_now__" : "今才",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "時間前",
        "__day__" : "日前",
        "__week__" : "週間前",
        "__month__" : "ヶ月前",
        "__year__" : "年前",
        "__filter__" : "フィルター",
        "__show_incomplete_tasks_only__" : "未完了のタスクのみを表示",
        "__show_completed_tasks_only__" : "完了したタスクのみを表示",
        "__task__" : "タスク",
        "__report__" : "報告",
        "__show_hide_side_nav__" : "サイドナビゲーションの表示/非表示",
        "__btn_week__" : "週",
        "__btn_month__" : "月",
        "__btn_year__" : "年",
        "__btn_activity__" : "活動",
        "__btn_quantity__" : "量",
        "__time_period__" : "期間",
        "__incompleted__" : "不完全",
        "__completed__" : "完了",
        "__total__" : "トータル"
    },
    "kr" : {
        "name" : "한국어",
        "locale" : "ko",
        "__language__" : "언어",
        "__theme__" : "주제",
        "__opacity__" : "불투명도",
        "__custom_settings__" : "사용자 지정 설정",
        "__custom_settings_desc__" : "버튼을 클릭하여 정렬, 핀 및 테마를 복원합니다.",
        "__restore__" : "복원",
        "__data_storage__" : "데이터 스토리지",
        "__disk_space_usage__" : "디스크 공간 사용량 : ",
        "__click_to_remove__" : "KB, 버튼을 클릭하여 모든 데이터를 제거합니다.",
        "__clear_all_data__" : "모든 데이터 지우기",
        "__show_hide_list__" : "목록 표시/숨기기",
        "__always_on_top__" : "항상 맨 위에",
        "__minimize__" : "최소화",
        "__quit__" : "사임하다",
        "__create__" : "창조하다",
        "__new_list__" : "새 목록",
        "__settings__" : "설정",
        "__pin__" : "핀",
        "__unpin__" : "고정 해제",
        "__new_subtask__" : "새 하위 작업",
        "__remove__" : "제거하다",
        "__just_now__" : "방금",
        "__sec__" : "초",
        "__min__" : "분",
        "__hr__" : "시간",
        "__day__" : "하루",
        "__week__" : "주",
        "__month__" : "달",
        "__year__" : "년",
        "__filter__" : "필터",
        "__show_incomplete_tasks_only__" : "완료되지 않은 작업만 표시",
        "__show_completed_tasks_only__" : "완료된 작업만 표시",
        "__task__" : "과업",
        "__report__" : "보고서",
        "__show_hide_side_nav__" : "측면 탐색 표시/숨기기",
        "__btn_week__" : "주",
        "__btn_month__" : "달",
        "__btn_year__" : "년",
        "__btn_activity__" : "활동",
        "__btn_quantity__" : "양",
        "__time_period__" : "기간",
        "__incompleted__" : "불완전",
        "__completed__" : "완료",
        "__total__" : "합계"
    },
    "pk" : {
        "name" : "اردو",
        "locale" : "ur",
        "__language__" : "زبان",
        "__theme__" : "موضوع",
        "__opacity__" : "غیر شفاف",
        "__custom_settings__" : "اپنی مرضی کے مطابق ترتیبات",
        "__custom_settings_desc__" : "قسمیں ، پن اور تھیم کو بحال کرنے کے لئے بٹن پر کلک کریں۔",
        "__restore__" : "بحالی",
        "__data_storage__" : "ڈیٹا",
        "__disk_space_usage__" : "ڈسک کی جگہ کا استعمال:",
        "__click_to_remove__" : "کے بی، تمام ڈیٹا کو ہٹانے کے لئے بٹن پر کلک کریں.",
        "__clear_all_data__" : "تمام اعداد و شمار صاف کریں",
        "__show_hide_list__" : "فہرست دکھائیں / چھپائیں",
        "__always_on_top__" : "ہمیشہ سب سے اوپر",
        "__minimize__" : "کم سے کم",
        "__quit__" : "ادا کرنا",
        "__create__" : "تخلیق",
        "__new_list__" : "نئی فہرست",
        "__settings__" : "سیٹنگیں",
        "__pin__" : "کیل",
        "__unpin__" : "راحت",
        "__new_subtask__" : "نیا ذیلی ٹاسک",
        "__remove__" : "ہٹانا",
        "__just_now__" : "ابھی",
        "__sec__" : "سیکنڈ",
        "__min__" : "منٹ",
        "__hr__" : "گھنٹے",
        "__day__" : "دن",
        "__week__" : "ہفتہ",
        "__month__" : "مہینہ",
        "__year__" : "سال",
        "__filter__" : "فلٹر",
        "__show_incomplete_tasks_only__" : "صرف نامکمل کام دکھائیں",
        "__show_completed_tasks_only__" : "صرف مکمل شدہ کام دکھائیں",
        "__task__" : "دنده",
        "__report__" : "راپور",
        "__show_hide_side_nav__" : "د څنګ چلونې ښودل  پټول",
        "__btn_week__" : "اونۍ",
        "__btn_month__" : "میاشت",
        "__btn_year__" : "کال",
        "__btn_activity__" : "فعالیت",
        "__btn_quantity__" : "مقدار",
        "__time_period__" : "د وخت دوره",
        "__incompleted__" : "نابشپړ",
        "__completed__" : "بشپړ",
        "__total__" : "ټول"
    },
    "pt" : {
        "name" : "Português",
        "locale" : "pt",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidade",
        "__custom_settings__" : "Configurações personalizadas",
        "__custom_settings_desc__" : "Clique no botão para restaurar classificações, pinos e tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Armazenamento de dados",
        "__disk_space_usage__" : "Uso de espaço em disco:",
        "__click_to_remove__" : "KB, clique no botão para remover todos os dados.",
        "__clear_all_data__" : "Limpar todos os dados",
        "__show_hide_list__" : "Mostrar / Ocultar Lista",
        "__always_on_top__" : "Sempre no topo",
        "__minimize__" : "Minimizar",
        "__quit__" : "Desistir",
        "__create__" : "Criar tarefa",
        "__new_list__" : "Nova lista",
        "__settings__" : "Configurações",
        "__pin__" : "Pino",
        "__unpin__" : "Desafixar",
        "__new_subtask__" : "Nova subtarefa",
        "__remove__" : "Remover",
        "__just_now__" : "só agora",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "dias",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "ano",
        "__filter__" : "Filtrar",
        "__show_incomplete_tasks_only__" : "Mostrar apenas tarefas incompletas",
        "__show_completed_tasks_only__" : "Mostrar apenas tarefas concluídas",
        "__task__" : "Tarefa",
        "__report__" : "Relatório",
        "__show_hide_side_nav__" : "Mostrar / Ocultar navegação lateral",
        "__btn_week__" : "Semana",
        "__btn_month__" : "Mês",
        "__btn_year__" : "Ano",
        "__btn_activity__" : "Atividade",
        "__btn_quantity__" : "Quantidade",
        "__time_period__" : "Período de tempo",
        "__incompleted__" : "Incompleto",
        "__completed__" : "Concluída",
        "__total__" : "Total"
    },
    "ru" : {
        "name" : "Русский",
        "locale" : "ru",
        "__language__" : "Язык",
        "__theme__" : "Тема",
        "__opacity__" : "Непрозрачность",
        "__custom_settings__" : "Пользовательские настройки",
        "__custom_settings_desc__" : "Нажмите кнопку, чтобы восстановить сортировку, булавки и тему.",
        "__restore__" : "Восстанавливать",
        "__data_storage__" : "Хранение данных",
        "__disk_space_usage__" : "Использование дискового пространства:",
        "__click_to_remove__" : "KB, нажмите кнопку, чтобы удалить все данные.",
        "__clear_all_data__" : "Очистите все данные",
        "__show_hide_list__" : "Показать / Скрыть список",
        "__always_on_top__" : "Всегда на высоте",
        "__minimize__" : "Минимизировать",
        "__quit__" : "Покидать",
        "__create__" : "Создавать",
        "__new_list__" : "Новый список",
        "__settings__" : "Параметры",
        "__pin__" : "Булавка",
        "__unpin__" : "Откалывать",
        "__new_subtask__" : "Новая подзадача",
        "__remove__" : "Убирать",
        "__just_now__" : "только что",
        "__sec__" : "секунды назад",
        "__min__" : "минуты назад",
        "__hr__" : "часа назад",
        "__day__" : "дня назад",
        "__week__" : "недели назад",
        "__month__" : "месяц назад",
        "__year__" : "год назад",
        "__filter__" : "Фильтр",
        "__show_incomplete_tasks_only__" : "Показывать только незавершенные задачи",
        "__show_completed_tasks_only__" : "Показывать только выполненные задачи",
        "__task__" : "Задача",
        "__report__" : "Сообщать",
        "__show_hide_side_nav__" : "Показать / скрыть боковую навигацию",
        "__btn_week__" : "Неделя",
        "__btn_month__" : "Месяц",
        "__btn_year__" : "Год",
        "__btn_activity__" : "Активность",
        "__btn_quantity__" : "Количество",
        "__time_period__" : "Период времени",
        "__incompleted__" : "Неполный",
        "__completed__" : "Завершённый",
        "__total__" : "Итог"
    },
    "zhCN" : {
        "name" : "简体中文",
        "locale" : "zh_cn",
        "__language__" : "语言",
        "__theme__" : "主题",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自定义设置",
        "__custom_settings_desc__" : "单击按钮以恢复排序，图钉和主题。",
        "__restore__" : "恢复",
        "__data_storage__" : "数据存储",
        "__disk_space_usage__" : "磁盘空间使用量：",
        "__click_to_remove__" : "KB, 单击按钮删除所有数据。",
        "__clear_all_data__" : "清除所有数据",
        "__show_hide_list__" : "显示/隐藏列表",
        "__always_on_top__" : "总在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "新建任务",
        "__new_list__" : "新建列表",
        "__settings__" : "设置",
        "__pin__" : "置顶",
        "__unpin__" : "取消置顶",
        "__new_subtask__" : "新建子任务",
        "__remove__" : "移除",
        "__just_now__" : "刚刚",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "小时前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前",
        "__filter__" : "筛选",
        "__show_incomplete_tasks_only__" : "仅显示未完成的任务",
        "__show_completed_tasks_only__" : "仅显示已完成的任务",
        "__task__" : "任务",
        "__report__" : "报表",
        "__show_hide_side_nav__" : "显示/隐藏侧边导航栏",
        "__btn_week__" : "周",
        "__btn_month__" : "月",
        "__btn_year__" : "年",
        "__btn_activity__" : "活跃",
        "__btn_quantity__" : "数量",
        "__time_period__" : "时间段",
        "__incompleted__" : "未完成",
        "__completed__" : "已完成",
        "__total__" : "总计"
    },
    "zhTW" : {
        "name" : "繁體中文",
        "locale" : "zh_tw",
        "__language__" : "語言",
        "__theme__" : "主題",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自訂設置",
        "__custom_settings_desc__" : "按下按鈕以恢復排序，圖釘和主題。",
        "__restore__" : "恢復",
        "__data_storage__" : "數據存儲",
        "__disk_space_usage__" : "磁碟空間使用量：",
        "__click_to_remove__" : "，按下按鈕刪除所有數據。",
        "__clear_all_data__" : "清除所有數據",
        "__show_hide_list__" : "顯示/隱藏清單",
        "__always_on_top__" : "總在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "創建任務",
        "__new_list__" : "創建新清單",
        "__settings__" : "設置",
        "__pin__" : "固定",
        "__unpin__" : "取消固定",
        "__new_subtask__" : "新建子任務",
        "__remove__" : "刪除",
        "__just_now__" : "剛才",
        "__sec__" : "秒前",
        "__min__" : "分鐘前",
        "__hr__" : "小時前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前",
        "__filter__" : "篩選",
        "__show_incomplete_tasks_only__" : "僅顯示未完成的任務",
        "__show_completed_tasks_only__" : "僅顯示已完成的任務",
        "__task__" : "任務",
        "__report__" : "報告",
        "__show_hide_side_nav__" : "顯示/隱藏側邊導航",
        "__btn_week__" : "周",
        "__btn_month__" : "月",
        "__btn_year__" : "年",
        "__btn_activity__" : "活動",
        "__btn_quantity__" : "數量",
        "__time_period__" : "時間段",
        "__incompleted__" : "未完成",
        "__completed__" : "已完成",
        "__total__" : "總計"
    }
}
