const Languages = {
    "ar" : {
        "name" : "العربية",
        "__language__" : "اللغة",
        "__theme__" : "موضوع",
        "__opacity__" : "العتامه",
        "__custom_settings__" : "إعدادات مخصصة",
        "__custom_settings_desc__" : "انقر فوق الزر لاستعادة الأنواع والدبابيس والسمة.",
        "__restore__" : "يستعيد",
        "__data_storage__" : "تخزين البيانات",
        "__disk_space_usage__" : "استخدام مساحة القرص:",
        "__click_to_remove__" : "KB ، انقر فوق الزر لإزالة جميع البيانات.",
        "__clear_all_data__" : "مسح جميع البيانات",
        "__show_hide_list__" : "إظهار / إخفاء القائمة",
        "__always_on_top__" : "دائما في المقدمة",
        "__minimize__" : "تصغير",
        "__quit__" : "انهاء",
        "__create__" : "خلق",
        "__new_list__" : "قائمة جديدة",
        "__settings__" : "اعدادات",
        "__pin__" : "دبوس",
        "__unpin__" : "حذف",
        "__new_subtask__" : "مهمة فرعية جديدة",
        "__remove__" : "أبعد",
        "__just_now__" : "منذ لحظة واحدة",
        "__sec__" : "ثانية",
        "__min__" : "دقائق",
        "__hr__" : "ساعات",
        "__day__" : "أيام",
        "__week__" : "أسابيع",
        "__month__" : "أشهر",
        "__year__" : "سنوات"
    },
    "de" : {
        "name" : "Deutsch",
        "__language__" : "Sprache",
        "__theme__" : "Thema",
        "__opacity__" : "Undurchsichtigkeit",
        "__custom_settings__" : "Benutzerdefinierte Einstellungen",
        "__custom_settings_desc__" : "Klicken Sie auf die Schaltfläche, um Sorten, Pins und Themen wiederherzustellen.",
        "__restore__" : "Wiederherstellen",
        "__data_storage__" : "Datenspeicherung",
        "__disk_space_usage__" : "Speicherplatznutzung: ",
        "__click_to_remove__" : "KB, klicken Sie auf die Schaltfläche, um alle Daten zu entfernen.",
        "__clear_all_data__" : "Alle Daten löschen",
        "__show_hide_list__" : "Liste ein- / ausblenden",
        "__always_on_top__" : "Immer im Vordergrund",
        "__minimize__" : "Minimieren",
        "__quit__" : "Verlassen",
        "__create__" : "Aufgabe erstellen",
        "__new_list__" : "Neue Liste",
        "__settings__" : "Einstellungen",
        "__pin__" : "Stecknadel",
        "__unpin__" : "Losheften",
        "__new_subtask__" : "Neue Unteraufgabe",
        "__remove__" : "Entfernen",
        "__just_now__" : "gerade eben",
        "__sec__" : "Sekunden vor",
        "__min__" : "Minuten vor",
        "__hr__" : "Stunden vor",
        "__day__" : "Tagen vor",
        "__week__" : "Wochen vor",
        "__month__" : "Monate vor",
        "__year__" : "Jahr vor"
    },
    "en" : {
        "name" : "English",
        "__language__" : "Language",
        "__theme__" : "Theme",
        "__opacity__" : "Opacity",
        "__custom_settings__" : "Custom Settings",
        "__custom_settings_desc__" : "Click button to restore sorts, pins and theme.",
        "__restore__" : "Restore",
        "__data_storage__" : "Data Storage",
        "__disk_space_usage__" : "Disk space usage:",
        "__click_to_remove__" : "KB, click button to remove all the data.",
        "__clear_all_data__" : "Clear all data",
        "__show_hide_list__" : "Show / Hide List",
        "__always_on_top__" : "Always On Top",
        "__minimize__" : "Minimize",
        "__quit__" : "Quit",
        "__create__" : "Create",
        "__new_list__" : "New List",
        "__settings__" : "Settings",
        "__pin__" : "Pin",
        "__unpin__" : "Unpin",
        "__new_subtask__" : "New Subtask",
        "__remove__" : "Remove",
        "__just_now__" : "Just now",
        "__sec__" : "sec",
        "__min__" : "min",
        "__hr__" : "hr",
        "__day__" : "day",
        "__week__" : "week",
        "__month__" : "month",
        "__year__" : "year"
    },
    "es" : {
        "name" : "Español",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidad",
        "__custom_settings__" : "Ajustes personalizados",
        "__custom_settings_desc__" : "Haga clic en el botón para restaurar las clasificaciones, los pines y el tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Almacenamiento de datos",
        "__disk_space_usage__" : "Uso de espacio en disco:",
        "__click_to_remove__" : "KB, haga clic en el botón para eliminar todos los datos.",
        "__clear_all_data__" : "Borrar todos los datos",
        "__show_hide_list__" : "Mostrar / Ocultar lista",
        "__always_on_top__" : "Siempre en la cima",
        "__minimize__" : "Minimizar",
        "__quit__" : "Renunciar",
        "__create__" : "Crear tarea",
        "__new_list__" : "Nueva lista",
        "__settings__" : "Configuración",
        "__pin__" : "Anclar",
        "__unpin__" : "Desanclar",
        "__new_subtask__" : "Nueva subtarea",
        "__remove__" : "Eliminar",
        "__just_now__" : "hace un momento",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "días",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "año"
    },
    "fr" : {
        "name" : "Française",
        "__language__" : "Langue",
        "__theme__" : "Thème",
        "__opacity__" : "Opacité",
        "__custom_settings__" : "Paramètres personnalisés",
        "__custom_settings_desc__" : "Cliquez sur le bouton pour restaurer les tris, les épingles et le thème.",
        "__restore__" : "Restaurer",
        "__data_storage__" : "Stockage des données",
        "__disk_space_usage__" : "Utilisation de l'espace disque :",
        "__click_to_remove__" : "Ko, cliquez sur le bouton pour supprimer toutes les données.",
        "__clear_all_data__" : "Effacer toutes les données",
        "__show_hide_list__" : "Afficher / Masquer la liste",
        "__always_on_top__" : "Toujours au sommet",
        "__minimize__" : "Minimiser",
        "__quit__" : "Démissionner",
        "__create__" : "Créer une tâche",
        "__new_list__" : "Nouvelle liste",
        "__settings__" : "Paramètres",
        "__pin__" : "Épingler",
        "__unpin__" : "Désépingler",
        "__new_subtask__" : "Nouvelle sous-tâche",
        "__remove__" : "Enlever",
        "__just_now__" : "Il y a quelques instants",
        "__sec__" : "secondes",
        "__min__" : "minutes",
        "__hr__" : "heures",
        "__day__" : "jours",
        "__week__" : "semaines",
        "__month__" : "mois",
        "__year__" : "an"
    },
    "jp" : {
        "name" : "日本語",
        "__language__" : "言語",
        "__theme__" : "テーマ",
        "__opacity__" : "不透明",
        "__custom_settings__" : "カスタム設定",
        "__custom_settings_desc__" : "ボタンをクリックして、並べ替え、ピン、テーマを復元します。",
        "__restore__" : "戻す",
        "__data_storage__" : "データストレージ",
        "__disk_space_usage__" : "ディスク容量の使用量:",
        "__click_to_remove__" : "KB、ボタンをクリックしてすべてのデータを削除します。",
        "__clear_all_data__" : "すべてのデータをクリアする",
        "__show_hide_list__" : "リストの表示/非表示",
        "__always_on_top__" : "常にトップに",
        "__minimize__" : "最小化する",
        "__quit__" : "辞める",
        "__create__" : "タスクを作成",
        "__new_list__" : "新規リスト",
        "__settings__" : "設定",
        "__pin__" : "ピン",
        "__unpin__" : "解除",
        "__new_subtask__" : "新規サブタスク",
        "__remove__" : "取り去る",
        "__just_now__" : "今才",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "時間前",
        "__day__" : "日前",
        "__week__" : "週間前",
        "__month__" : "ヶ月前",
        "__year__" : "年前"
    },
    "pt" : {
        "name" : "Português",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidade",
        "__custom_settings__" : "Configurações personalizadas",
        "__custom_settings_desc__" : "Clique no botão para restaurar classificações, pinos e tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Armazenamento de dados",
        "__disk_space_usage__" : "Uso de espaço em disco:",
        "__click_to_remove__" : "KB, clique no botão para remover todos os dados.",
        "__clear_all_data__" : "Limpar todos os dados",
        "__show_hide_list__" : "Mostrar / Ocultar Lista",
        "__always_on_top__" : "Sempre no topo",
        "__minimize__" : "Minimizar",
        "__quit__" : "Desistir",
        "__create__" : "Criar tarefa",
        "__new_list__" : "Nova lista",
        "__settings__" : "Configurações",
        "__pin__" : "Pino",
        "__unpin__" : "Desafixar",
        "__new_subtask__" : "Nova subtarefa",
        "__remove__" : "Remover",
        "__just_now__" : "só agora",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "dias",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "ano"
    },
    "ru" : {
        "name" : "Русский",
        "__language__" : "Язык",
        "__theme__" : "Тема",
        "__opacity__" : "Непрозрачность",
        "__custom_settings__" : "Пользовательские настройки",
        "__custom_settings_desc__" : "Нажмите кнопку, чтобы восстановить сортировку, булавки и тему.",
        "__restore__" : "Восстанавливать",
        "__data_storage__" : "Хранение данных",
        "__disk_space_usage__" : "Использование дискового пространства:",
        "__click_to_remove__" : "KB, нажмите кнопку, чтобы удалить все данные.",
        "__clear_all_data__" : "Очистите все данные",
        "__show_hide_list__" : "Показать / Скрыть список",
        "__always_on_top__" : "Всегда на высоте",
        "__minimize__" : "Минимизировать",
        "__quit__" : "Покидать",
        "__create__" : "Создавать",
        "__new_list__" : "Новый список",
        "__settings__" : "Параметры",
        "__pin__" : "Булавка",
        "__unpin__" : "Откалывать",
        "__new_subtask__" : "Новая подзадача",
        "__remove__" : "Убирать",
        "__just_now__" : "только что",
        "__sec__" : "секунды назад",
        "__min__" : "минуты назад",
        "__hr__" : "часа назад",
        "__day__" : "дня назад",
        "__week__" : "недели назад",
        "__month__" : "месяц назад",
        "__year__" : "год назад"
    },
    "zhCN" : {
        "name" : "简体中文",
        "__language__" : "语言",
        "__theme__" : "主题",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自定义设置",
        "__custom_settings_desc__" : "单击按钮以恢复排序，图钉和主题。",
        "__restore__" : "恢复",
        "__data_storage__" : "数据存储",
        "__disk_space_usage__" : "磁盘空间使用量：",
        "__click_to_remove__" : "KB, 单击按钮删除所有数据。",
        "__clear_all_data__" : "清除所有数据",
        "__show_hide_list__" : "显示/隐藏列表",
        "__always_on_top__" : "总在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "新建任务",
        "__new_list__" : "新建列表",
        "__settings__" : "设置",
        "__pin__" : "置顶",
        "__unpin__" : "取消置顶",
        "__new_subtask__" : "新建子任务",
        "__remove__" : "移除",
        "__just_now__" : "刚刚",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "小时前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前"
    },
    "zhTW" : {
        "name" : "繁體中文",
        "__language__" : "語言",
        "__theme__" : "主題",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自訂設置",
        "__custom_settings_desc__" : "按下按鈕以恢復排序，圖釘和主題。",
        "__restore__" : "恢復",
        "__data_storage__" : "數據存儲",
        "__disk_space_usage__" : "磁碟空間使用量：",
        "__click_to_remove__" : "，按下按鈕刪除所有數據。",
        "__clear_all_data__" : "清除所有數據",
        "__show_hide_list__" : "顯示/隱藏清單",
        "__always_on_top__" : "總在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "創建任務",
        "__new_list__" : "創建新清單",
        "__settings__" : "設置",
        "__pin__" : "固定",
        "__unpin__" : "取消固定",
        "__new_subtask__" : "新建子任務",
        "__remove__" : "刪除",
        "__just_now__" : "剛才",
        "__sec__" : "秒前",
        "__min__" : "分鐘前",
        "__hr__" : "小時前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前"
    }
}
