const Languages = {
    "ar" : {
        "name" : "العربية",
        "__language__" : "اللغة",
        "__theme__" : "موضوع",
        "__opacity__" : "العتامه",
        "__custom_settings__" : "إعدادات مخصصة",
        "__custom_settings_desc__" : "انقر فوق الزر لاستعادة الأنواع والدبابيس والسمة.",
        "__restore__" : "يستعيد",
        "__data_storage__" : "تخزين البيانات",
        "__disk_space_usage__" : "استخدام مساحة القرص:",
        "__click_to_remove__" : "KB ، انقر فوق الزر لإزالة جميع البيانات.",
        "__clear_all_data__" : "مسح جميع البيانات",
        "__show_hide_list__" : "إظهار / إخفاء القائمة",
        "__always_on_top__" : "دائما في المقدمة",
        "__minimize__" : "تصغير",
        "__quit__" : "انهاء",
        "__create__" : "خلق",
        "__new_list__" : "قائمة جديدة",
        "__settings__" : "اعدادات",
        "__pin__" : "دبوس",
        "__unpin__" : "حذف",
        "__new_subtask__" : "مهمة فرعية جديدة",
        "__remove__" : "أبعد",
        "__just_now__" : "منذ لحظة واحدة",
        "__sec__" : "ثانية",
        "__min__" : "دقائق",
        "__hr__" : "ساعات",
        "__day__" : "أيام",
        "__week__" : "أسابيع",
        "__month__" : "أشهر",
        "__year__" : "سنوات",
        "__filter__" : "راووق"
    },
    "de" : {
        "name" : "Deutsch",
        "__language__" : "Sprache",
        "__theme__" : "Thema",
        "__opacity__" : "Undurchsichtigkeit",
        "__custom_settings__" : "Benutzerdefinierte Einstellungen",
        "__custom_settings_desc__" : "Klicken Sie auf die Schaltfläche, um Sorten, Pins und Themen wiederherzustellen.",
        "__restore__" : "Wiederherstellen",
        "__data_storage__" : "Datenspeicherung",
        "__disk_space_usage__" : "Speicherplatznutzung: ",
        "__click_to_remove__" : "KB, klicken Sie auf die Schaltfläche, um alle Daten zu entfernen.",
        "__clear_all_data__" : "Alle Daten löschen",
        "__show_hide_list__" : "Liste ein- / ausblenden",
        "__always_on_top__" : "Immer im Vordergrund",
        "__minimize__" : "Minimieren",
        "__quit__" : "Verlassen",
        "__create__" : "Aufgabe erstellen",
        "__new_list__" : "Neue Liste",
        "__settings__" : "Einstellungen",
        "__pin__" : "Stecknadel",
        "__unpin__" : "Losheften",
        "__new_subtask__" : "Neue Unteraufgabe",
        "__remove__" : "Entfernen",
        "__just_now__" : "gerade eben",
        "__sec__" : "Sekunden vor",
        "__min__" : "Minuten vor",
        "__hr__" : "Stunden vor",
        "__day__" : "Tagen vor",
        "__week__" : "Wochen vor",
        "__month__" : "Monate vor",
        "__year__" : "Jahr vor",
        "__filter__" : "Filter"
    },
    "en" : {
        "name" : "English",
        "__language__" : "Language",
        "__theme__" : "Theme",
        "__opacity__" : "Opacity",
        "__custom_settings__" : "Custom Settings",
        "__custom_settings_desc__" : "Click button to restore sorts, pins and theme.",
        "__restore__" : "Restore",
        "__data_storage__" : "Data Storage",
        "__disk_space_usage__" : "Disk space usage:",
        "__click_to_remove__" : "KB, click button to remove all the data.",
        "__clear_all_data__" : "Clear all data",
        "__show_hide_list__" : "Show / Hide List",
        "__always_on_top__" : "Always On Top",
        "__minimize__" : "Minimize",
        "__quit__" : "Quit",
        "__create__" : "Create",
        "__new_list__" : "New List",
        "__settings__" : "Settings",
        "__pin__" : "Pin",
        "__unpin__" : "Unpin",
        "__new_subtask__" : "New Subtask",
        "__remove__" : "Remove",
        "__just_now__" : "Just now",
        "__sec__" : "sec",
        "__min__" : "min",
        "__hr__" : "hr",
        "__day__" : "day",
        "__week__" : "week",
        "__month__" : "month",
        "__year__" : "year",
        "__filter__" : "Filter"
    },
    "es" : {
        "name" : "Español",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidad",
        "__custom_settings__" : "Ajustes personalizados",
        "__custom_settings_desc__" : "Haga clic en el botón para restaurar las clasificaciones, los pines y el tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Almacenamiento de datos",
        "__disk_space_usage__" : "Uso de espacio en disco:",
        "__click_to_remove__" : "KB, haga clic en el botón para eliminar todos los datos.",
        "__clear_all_data__" : "Borrar todos los datos",
        "__show_hide_list__" : "Mostrar / Ocultar lista",
        "__always_on_top__" : "Siempre en la cima",
        "__minimize__" : "Minimizar",
        "__quit__" : "Renunciar",
        "__create__" : "Crear tarea",
        "__new_list__" : "Nueva lista",
        "__settings__" : "Configuración",
        "__pin__" : "Anclar",
        "__unpin__" : "Desanclar",
        "__new_subtask__" : "Nueva subtarea",
        "__remove__" : "Eliminar",
        "__just_now__" : "hace un momento",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "días",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "año",
        "__filter__" : "Filtro"
    },
    "fr" : {
        "name" : "Française",
        "__language__" : "Langue",
        "__theme__" : "Thème",
        "__opacity__" : "Opacité",
        "__custom_settings__" : "Paramètres personnalisés",
        "__custom_settings_desc__" : "Cliquez sur le bouton pour restaurer les tris, les épingles et le thème.",
        "__restore__" : "Restaurer",
        "__data_storage__" : "Stockage des données",
        "__disk_space_usage__" : "Utilisation de l'espace disque :",
        "__click_to_remove__" : "Ko, cliquez sur le bouton pour supprimer toutes les données.",
        "__clear_all_data__" : "Effacer toutes les données",
        "__show_hide_list__" : "Afficher / Masquer la liste",
        "__always_on_top__" : "Toujours au sommet",
        "__minimize__" : "Minimiser",
        "__quit__" : "Démissionner",
        "__create__" : "Créer une tâche",
        "__new_list__" : "Nouvelle liste",
        "__settings__" : "Paramètres",
        "__pin__" : "Épingler",
        "__unpin__" : "Désépingler",
        "__new_subtask__" : "Nouvelle sous-tâche",
        "__remove__" : "Enlever",
        "__just_now__" : "Il y a quelques instants",
        "__sec__" : "secondes",
        "__min__" : "minutes",
        "__hr__" : "heures",
        "__day__" : "jours",
        "__week__" : "semaines",
        "__month__" : "mois",
        "__year__" : "an",
        "__filter__" : "Filtre"
    },
    "in" : {
        "name" : "हिंदी",
        "__language__" : "भाषा",
        "__theme__" : "विषय",
        "__opacity__" : "अस्पष्टता",
        "__custom_settings__" : "कस्टम सेटिंग्स",
        "__custom_settings_desc__" : "प्रकार, पिन और विषय को पुनर्स्थापित करने के लिए बटन पर क्लिक करें।",
        "__restore__" : "पुनर्स्थापित करना",
        "__data_storage__" : "डेटा भंडारण",
        "__disk_space_usage__" : "डिस्क स्थान उपयोग:",
        "__click_to_remove__" : "KB, सभी डेटा को हटाने के लिए बटन पर क्लिक करें।",
        "__clear_all_data__" : "सभी डेटा साफ़ करें",
        "__show_hide_list__" : "सूची दिखाएं/छुपाएं",
        "__always_on_top__" : "हमेशा शीर्ष पर",
        "__minimize__" : "कम करके बताना",
        "__quit__" : "छोड़ना",
        "__create__" : "बनाना",
        "__new_list__" : "नई सूची",
        "__settings__" : "सेटिंग्स",
        "__pin__" : "पिन",
        "__unpin__" : "अनपिन",
        "__new_subtask__" : "नया उपकार्य",
        "__remove__" : "हटाना",
        "__just_now__" : "अभी-अभी",
        "__sec__" : "सेकंड",
        "__min__" : "मिनट",
        "__hr__" : "घंटे",
        "__day__" : "दिन",
        "__week__" : "कार्य-सप्‍ताह",
        "__month__" : "महीना",
        "__year__" : "सालों",
        "__filter__" : "छानना"
    },
    "it" : {
        "name" : "Italiana",
        "__language__" : "Lingua",
        "__theme__" : "Tema",
        "__opacity__" : "Opacità",
        "__custom_settings__" : "Impostazioni personalizzate",
        "__custom_settings_desc__" : "Fare clic sul pulsante per ripristinare ordinamenti, pin e tema.",
        "__restore__" : "Restaurare",
        "__data_storage__" : "Archiviazione dei dati",
        "__disk_space_usage__" : "Utilizzo dello spazio su disco:",
        "__click_to_remove__" : "KB, fare clic sul pulsante per rimuovere tutti i dati.",
        "__clear_all_data__" : "Cancella tutti i dati",
        "__show_hide_list__" : "Mostra / Nascondi elenco",
        "__always_on_top__" : "Sempre in primo piano",
        "__minimize__" : "Minimizzare",
        "__quit__" : "Dimettersi",
        "__create__" : "Creare",
        "__new_list__" : "Nuovo elenco",
        "__settings__" : "Impostazioni",
        "__pin__" : "Spilla",
        "__unpin__" : "Rimuovere",
        "__new_subtask__" : "Nuova sottoattività",
        "__remove__" : "Togliere",
        "__just_now__" : "Poco fa",
        "__sec__" : "secondo",
        "__min__" : "minuta",
        "__hr__" : "orario",
        "__day__" : "giorno",
        "__week__" : "settimana",
        "__month__" : "mese",
        "__year__" : "anno",
        "__filter__" : "Filtro"
    },
    "jp" : {
        "name" : "日本語",
        "__language__" : "言語",
        "__theme__" : "テーマ",
        "__opacity__" : "不透明",
        "__custom_settings__" : "カスタム設定",
        "__custom_settings_desc__" : "ボタンをクリックして、並べ替え、ピン、テーマを復元します。",
        "__restore__" : "戻す",
        "__data_storage__" : "データストレージ",
        "__disk_space_usage__" : "ディスク容量の使用量:",
        "__click_to_remove__" : "KB、ボタンをクリックしてすべてのデータを削除します。",
        "__clear_all_data__" : "すべてのデータをクリアする",
        "__show_hide_list__" : "リストの表示/非表示",
        "__always_on_top__" : "常にトップに",
        "__minimize__" : "最小化する",
        "__quit__" : "辞める",
        "__create__" : "タスクを作成",
        "__new_list__" : "新規リスト",
        "__settings__" : "設定",
        "__pin__" : "ピン",
        "__unpin__" : "解除",
        "__new_subtask__" : "新規サブタスク",
        "__remove__" : "取り去る",
        "__just_now__" : "今才",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "時間前",
        "__day__" : "日前",
        "__week__" : "週間前",
        "__month__" : "ヶ月前",
        "__year__" : "年前",
        "__filter__" : "フィルター"
    },
    "kr" : {
        "name" : "한국어",
        "__language__" : "언어",
        "__theme__" : "주제",
        "__opacity__" : "불투명도",
        "__custom_settings__" : "사용자 지정 설정",
        "__custom_settings_desc__" : "버튼을 클릭하여 정렬, 핀 및 테마를 복원합니다.",
        "__restore__" : "복원",
        "__data_storage__" : "데이터 스토리지",
        "__disk_space_usage__" : "디스크 공간 사용량 : ",
        "__click_to_remove__" : "KB, 버튼을 클릭하여 모든 데이터를 제거합니다.",
        "__clear_all_data__" : "모든 데이터 지우기",
        "__show_hide_list__" : "목록 표시/숨기기",
        "__always_on_top__" : "항상 맨 위에",
        "__minimize__" : "최소화",
        "__quit__" : "사임하다",
        "__create__" : "창조하다",
        "__new_list__" : "새 목록",
        "__settings__" : "설정",
        "__pin__" : "핀",
        "__unpin__" : "고정 해제",
        "__new_subtask__" : "새 하위 작업",
        "__remove__" : "제거하다",
        "__just_now__" : "방금",
        "__sec__" : "초",
        "__min__" : "분",
        "__hr__" : "시간",
        "__day__" : "하루",
        "__week__" : "주",
        "__month__" : "달",
        "__year__" : "년",
        "__filter__" : "필터"
    },
    "pk" : {
        "name" : "اردو",
        "__language__" : "زبان",
        "__theme__" : "موضوع",
        "__opacity__" : "غیر شفاف",
        "__custom_settings__" : "اپنی مرضی کے مطابق ترتیبات",
        "__custom_settings_desc__" : "قسمیں ، پن اور تھیم کو بحال کرنے کے لئے بٹن پر کلک کریں۔",
        "__restore__" : "بحالی",
        "__data_storage__" : "ڈیٹا",
        "__disk_space_usage__" : "ڈسک کی جگہ کا استعمال:",
        "__click_to_remove__" : "کے بی، تمام ڈیٹا کو ہٹانے کے لئے بٹن پر کلک کریں.",
        "__clear_all_data__" : "تمام اعداد و شمار صاف کریں",
        "__show_hide_list__" : "فہرست دکھائیں / چھپائیں",
        "__always_on_top__" : "ہمیشہ سب سے اوپر",
        "__minimize__" : "کم سے کم",
        "__quit__" : "ادا کرنا",
        "__create__" : "تخلیق",
        "__new_list__" : "نئی فہرست",
        "__settings__" : "سیٹنگیں",
        "__pin__" : "کیل",
        "__unpin__" : "راحت",
        "__new_subtask__" : "نیا ذیلی ٹاسک",
        "__remove__" : "ہٹانا",
        "__just_now__" : "ابھی",
        "__sec__" : "سیکنڈ",
        "__min__" : "منٹ",
        "__hr__" : "گھنٹے",
        "__day__" : "دن",
        "__week__" : "ہفتہ",
        "__month__" : "مہینہ",
        "__year__" : "سال",
        "__filter__" : "فلٹر"
    },
    "pt" : {
        "name" : "Português",
        "__language__" : "Idioma",
        "__theme__" : "Tema",
        "__opacity__" : "Opacidade",
        "__custom_settings__" : "Configurações personalizadas",
        "__custom_settings_desc__" : "Clique no botão para restaurar classificações, pinos e tema.",
        "__restore__" : "Restaurar",
        "__data_storage__" : "Armazenamento de dados",
        "__disk_space_usage__" : "Uso de espaço em disco:",
        "__click_to_remove__" : "KB, clique no botão para remover todos os dados.",
        "__clear_all_data__" : "Limpar todos os dados",
        "__show_hide_list__" : "Mostrar / Ocultar Lista",
        "__always_on_top__" : "Sempre no topo",
        "__minimize__" : "Minimizar",
        "__quit__" : "Desistir",
        "__create__" : "Criar tarefa",
        "__new_list__" : "Nova lista",
        "__settings__" : "Configurações",
        "__pin__" : "Pino",
        "__unpin__" : "Desafixar",
        "__new_subtask__" : "Nova subtarefa",
        "__remove__" : "Remover",
        "__just_now__" : "só agora",
        "__sec__" : "segundos",
        "__min__" : "minutos",
        "__hr__" : "horas",
        "__day__" : "dias",
        "__week__" : "semanas",
        "__month__" : "meses",
        "__year__" : "ano",
        "__filter__" : "Filtrar"
    },
    "ru" : {
        "name" : "Русский",
        "__language__" : "Язык",
        "__theme__" : "Тема",
        "__opacity__" : "Непрозрачность",
        "__custom_settings__" : "Пользовательские настройки",
        "__custom_settings_desc__" : "Нажмите кнопку, чтобы восстановить сортировку, булавки и тему.",
        "__restore__" : "Восстанавливать",
        "__data_storage__" : "Хранение данных",
        "__disk_space_usage__" : "Использование дискового пространства:",
        "__click_to_remove__" : "KB, нажмите кнопку, чтобы удалить все данные.",
        "__clear_all_data__" : "Очистите все данные",
        "__show_hide_list__" : "Показать / Скрыть список",
        "__always_on_top__" : "Всегда на высоте",
        "__minimize__" : "Минимизировать",
        "__quit__" : "Покидать",
        "__create__" : "Создавать",
        "__new_list__" : "Новый список",
        "__settings__" : "Параметры",
        "__pin__" : "Булавка",
        "__unpin__" : "Откалывать",
        "__new_subtask__" : "Новая подзадача",
        "__remove__" : "Убирать",
        "__just_now__" : "только что",
        "__sec__" : "секунды назад",
        "__min__" : "минуты назад",
        "__hr__" : "часа назад",
        "__day__" : "дня назад",
        "__week__" : "недели назад",
        "__month__" : "месяц назад",
        "__year__" : "год назад",
        "__filter__" : "Фильтр"
    },
    "zhCN" : {
        "name" : "简体中文",
        "__language__" : "语言",
        "__theme__" : "主题",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自定义设置",
        "__custom_settings_desc__" : "单击按钮以恢复排序，图钉和主题。",
        "__restore__" : "恢复",
        "__data_storage__" : "数据存储",
        "__disk_space_usage__" : "磁盘空间使用量：",
        "__click_to_remove__" : "KB, 单击按钮删除所有数据。",
        "__clear_all_data__" : "清除所有数据",
        "__show_hide_list__" : "显示/隐藏列表",
        "__always_on_top__" : "总在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "新建任务",
        "__new_list__" : "新建列表",
        "__settings__" : "设置",
        "__pin__" : "置顶",
        "__unpin__" : "取消置顶",
        "__new_subtask__" : "新建子任务",
        "__remove__" : "移除",
        "__just_now__" : "刚刚",
        "__sec__" : "秒前",
        "__min__" : "分前",
        "__hr__" : "小时前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前",
        "__filter__" : "筛选"
    },
    "zhTW" : {
        "name" : "繁體中文",
        "__language__" : "語言",
        "__theme__" : "主題",
        "__opacity__" : "不透明度",
        "__custom_settings__" : "自訂設置",
        "__custom_settings_desc__" : "按下按鈕以恢復排序，圖釘和主題。",
        "__restore__" : "恢復",
        "__data_storage__" : "數據存儲",
        "__disk_space_usage__" : "磁碟空間使用量：",
        "__click_to_remove__" : "，按下按鈕刪除所有數據。",
        "__clear_all_data__" : "清除所有數據",
        "__show_hide_list__" : "顯示/隱藏清單",
        "__always_on_top__" : "總在最前",
        "__minimize__" : "最小化",
        "__quit__" : "退出",
        "__create__" : "創建任務",
        "__new_list__" : "創建新清單",
        "__settings__" : "設置",
        "__pin__" : "固定",
        "__unpin__" : "取消固定",
        "__new_subtask__" : "新建子任務",
        "__remove__" : "刪除",
        "__just_now__" : "剛才",
        "__sec__" : "秒前",
        "__min__" : "分鐘前",
        "__hr__" : "小時前",
        "__day__" : "天前",
        "__week__" : "周前",
        "__month__" : "月前",
        "__year__" : "年前",
        "__filter__" : "篩選"
    }
}
